### ISSUE TITLE
Setting web3j.httpTimeoutSeconds to 0 still results in a timeout

### ISSUE THREAD

**Issue by parapluplu** [web3j/web3j-spring-boot-starter#10]
I've configured the property `web3j.httpTimeoutSeconds` to `0`. According to the documentation this will result in no timeout. However I still get a timeout, if the parity node is not responding fast enough:

```
2018-05-02 10:59:48.450 ERROR 1 --- [pool-6-thread-2] org.web3j.protocol.core.filters.Filter   : Error sending request

org.web3j.protocol.core.filters.FilterException: Error sending request
        at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:156) ~[core-3.3.1.jar!/:na]
        at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:110) ~[core-3.3.1.jar!/:na]
        at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:75) ~[core-3.3.1.jar!/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
Caused by: java.net.ConnectException: Failed to connect to **MY_IP_HERE**:8545
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:225) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.RealCall.execute(RealCall.java:69) ~[okhttp-3.8.1.jar!/:na]
        at org.web3j.protocol.http.HttpService.performIO(HttpService.java:104) ~[core-3.3.1.jar!/:na]
        at org.web3j.protocol.Service.send(Service.java:31) ~[core-3.3.1.jar!/:na]
        at org.web3j.protocol.core.Request.send(Request.java:71) ~[core-3.3.1.jar!/:na]
        at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:108) ~[core-3.3.1.jar!/:na]
        ... 8 common frames omitted
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_151]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_151]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_151]
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124) ~[okhttp-3.8.1.jar!/:na]
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223) ~[okhttp-3.8.1.jar!/:na]
        ... 29 common frames omitted

```

**Comment by iikirilov** [comment]
is this still an issue?

**Comment by iikirilov** [comment]
Closing due to inactivity.
