### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/provider/digest/Keccak$DigestKeccak

### ISSUE THREAD

**Issue by yangboz** [web3j/web3j-spring-boot-starter#11]
when using:
```
<dependency>
<groupId>org.web3j</groupId>
<artifactId>web3j-spring-boot-starter</artifactId>
<version>1.6.0</version>
</dependency>
```
calling :  

```
Credentials credentials = WalletUtils.loadCredentials(
```

but it throws:

```
20870: ERROR [dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/provider/digest/Keccak$DigestKeccak] with root cause
java.lang.ClassNotFoundException: org.bouncycastle.jcajce.provider.digest.Keccak$DigestKeccak
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.web3j.crypto.Wallet.generateMac(Wallet.java:173)
	at org.web3j.crypto.Wallet.decrypt(Wallet.java:211)
	at org.web3j.crypto.WalletUtils.loadCredentials(WalletUtils.java:113)
	at org.web3j.crypto.WalletUtils.loadCredentials(WalletUtils.java:107)
···

**Comment by yuriyouzhou** [comment]
@yangboz  +1.. did you fix it?

**Comment by smartkit** [comment]
not yet...

**Comment by iikirilov** [comment]
is this still an issue? the project has been updated since

**Comment by iikirilov** [comment]
Closing due to inactivity.
